### PR TITLE
Update SHADERed to 1.4.2

### PR DESCRIPTION
**Pull request by marknefedov**
update to version 1.4.2

### CODE REVIEW

**Comment by marknefedov** [comment]
To find GLM, somehow prefix need to have `<path to glm root>/cmake/glm`, and glmConfig needs be copied as GLMConfig, since upstream uses upper-case findpackage, but i have no idea how to do this through flatpak config.

**Comment by Calinou** [comment]
> To find GLM, somehow prefix need to have <path to glm root>/cmake/glm, and glmConfig needs be copied as GLMConfig, since upstream uses upper-case findpackage, but i have no idea how to do this through flatpak config.

See also https://github.com/flathub/org.shadered.SHADERed/pull/2 where I tried to update GLM, but failed. The CMake install step was removed from recent GLM versions; see https://github.com/g-truc/glm/pull/968 which tried to reimplement it.

If it's possible to keep our current GLM version, we should do that instead.

**Comment by marknefedov** [comment]
There is a fix for Experimental features in https://github.com/g-truc/glm#glm-0995---2019-04-01, that fixes https://flathub.org/builds/#/builders/12/builds/4070, so guess we can try bump glm to 9.9.5, since install target was removed in 9.9.6.

**Comment by marknefedov** [comment]
Seems work fine on my machine.
screenshot

**Review by Calinou — APPROVED** [review]
Tested locally (Fedora 33), it works. Thanks a lot for upgrading the SHADERed Flatpak! :slightly_smiling_face:

**Pull request merged**
